# Generated by Django 2.2 on 2019-05-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='household_id',
        ),
    ]
