# Generated by Django 2.2 on 2019-05-07 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_remove_user_household_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='household_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tables.Household'),
            preserve_default=False,
        ),
    ]
